MyBehavior:
  trainer_type: ppo
  batch_size: 64
  buffer_size: 2048
  learning_rate: 3.0e-4
  beta: 5.0e-3
  epsilon: 0.2
  lambd: 0.95
  num_epoch: 3
  gamma: 0.99
  max_steps: 500000
  time_horizon: 64
  summary_freq: 10000
